apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mysql-55-centos7-volume-1 #must use this exact name!
spec: 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  rbd: 
    monitors: 
      - 192.168.122.133:6789
    pool: rbd
    image: foo
    user: admin
    secretRef: 
      name: ceph-secret
    fsType: ext4
    readOnly: false
